[package]
name = "blowfish"
version = "0.1.0"
authors = ["nilq <i.am@nilq.dk>"]

[dependencies]
log = "0.3.6"
quick-error = "1.0.0"
fnv = "1.0.3"
pretty = "0.2.0"
smallvec = "0.2.1"
collect-mac = "0.1.0"
